### ISSUE TITLE
Add Support for Cinnamon 2.6

### ISSUE THREAD

**Issue by kelebek333** [ConnerHansen/Flipper#2]
Could you add Cinnamon 2.6 support with editing metadata.json file

{
    "cinnamon-version": [
        "2.0",
        "2.1",
        "2.2",
        "2.3",
        "2.4",
        "2.6"
    ],
    "url": "https://github.com/ConnerHansen/Flipper",
    "uuid": "Flipper@connerdev",
    "name": "Flipper",
    "description": "Fancy workspace switching extension"
}

**Comment by ConnerHansen** [comment]
Resolved in 0.9
