### ISSUE TITLE
Add Support for Cinnamon 2.8

### ISSUE THREAD

**Issue by kelebek333** [ConnerHansen/Flipper#5]
Could you add Cinnamon 2.8 support with editing metadata.json file
{
    "last-edited": "1443405905", 
    "cinnamon-version": [
        "2.0", 
        "2.1", 
        "2.2", 
        "2.3", 
        "2.4", 
        "2.6",
        "2.8"
    ], 
    "url": "https://github.com/ConnerHansen/Flipper", 
    "uuid": "Flipper@connerdev", 
    "name": "Flipper", 
    "description": "Fancy workspace switching extension"
}

**Comment by ConnerHansen** [comment]
Added in support for Cinnamon 2.8
